# Generated by Django 2.0.9 on 2021-07-09 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('impressoras', '0001_initial'),
        ('setores', '0001_initial'),
        ('nobreaks', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patrimonio', models.CharField(max_length=6, unique=True)),
                ('modelo', models.CharField(choices=[('1', 'HP402'), ('2', 'Pro One'), ('3', 'Itautec')], max_length=14)),
                ('sistema', models.CharField(choices=[('1', 'Windows Xp'), ('2', 'Windows 7'), ('3', 'Windows 8'), ('4', 'Windows 10'), ('5', 'Linux')], max_length=10)),
                ('memoria', models.CharField(choices=[('2GB', '2GB'), ('4GB', '4GB'), ('6GB', '6GB'), ('8GB', '8GB'), ('12GB', '12GB')], max_length=5)),
                ('host', models.CharField(max_length=30, unique=True)),
                ('processador', models.CharField(choices=[('Dual Core', 'Dual Core'), ('intel I3', 'intel I3'), ('intel I5', 'intel I5'), ('intel I7', 'intel I7')], max_length=10)),
                ('office', models.CharField(choices=[('1', 'Office 2007'), ('2', 'Office 2010'), ('3', 'Office 2013'), ('4', 'Office 2016')], max_length=10)),
                ('antivirus', models.CharField(choices=[('KSP', 'Kaspersky'), ('KSF', 'Kaspersky Free'), ('AVS', 'Avast'), ('OUT', 'Outro')], max_length=30)),
                ('internet', models.CharField(choices=[('1', 'Rj45'), ('2', 'Wi-Fi')], max_length=4)),
                ('conexao_impressora', models.CharField(choices=[('1', 'Wi_Fi'), ('2', 'RJ-45'), ('3', 'Wi_Fi')], max_length=6)),
                ('ocs', models.CharField(max_length=3)),
                ('observacao', models.TextField()),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='setores.Setor')),
                ('impressora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='impressoras.Impressora')),
                ('nobreak', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='nobreaks.Nobreak')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.Usuario')),
            ],
        ),
    ]
