# Generated by Django 2.0.9 on 2021-07-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_setor', models.CharField(max_length=30, unique=True)),
                ('localizacao', models.CharField(choices=[('Subsolo', 'Subsolo'), ('Térreo', 'Térreo'), ('1º Andar', '1º Andar'), ('2º Andar', '2º Andar'), ('3º Andar', '3º Andar')], max_length=8)),
                ('grupo', models.CharField(max_length=30)),
            ],
        ),
    ]
