# Generated by Django 2.0.9 on 2021-07-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Impressora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patrimonio', models.CharField(max_length=6, unique=True)),
                ('modelo', models.CharField(choices=[('Epson L455', 'Epson L455'), ('HP 2055dn', 'HP 2055dn'), ('HP 2015', 'HP 2015'), ('HP 1200', 'HP 1200'), ('HP j2010', 'HP j2010'), ('HP M201', 'HP M201'), ('HP DESKJET 2546', 'HP DESKJET 2546'), ('HP CM1410', 'HP CM1410'), ('HP DESKJET 895', 'HP DESKJET 895'), ('HP PRO400', 'HP PRO400')], max_length=16)),
                ('mac', models.CharField(max_length=17, unique=True)),
                ('ip_impressora', models.CharField(max_length=16, unique=True)),
            ],
        ),
    ]
