# Generated by Django 2.0.9 on 2021-07-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nobreak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patrimonio', models.CharField(max_length=30, unique=True)),
                ('modelo_nobreak', models.CharField(choices=[('1', 'RAGTECH 1200Va'), ('2', 'APC 600Va')], max_length=3)),
            ],
        ),
    ]
